### ISSUE TITLE
Vendor eligibility requirements

### ISSUE THREAD

**Issue by lleger** [18F/tts-buy-code-review#1]
# Question/Comment

## Name and affiliation
CEO - [NewAperio](http://newaperio.com) - @newaperio

## Section of RFQ documents
N/A

## Question/Comment
What are the vendor eligibility requirements for submitting a proposal? Are only GSA Schedule 70 companies eligible to submit a proposal or is any company that is registered with SAM able to submit a bid? I’m trying to determine if we are eligible to participate in this bid.

**Comment by MichelleMcNellis** [comment]
Per the RFQ This solicitation is issued pursuant to the terms and conditions of the GSA Multiple Award Schedule (MAS), also known as Federal Supply Schedule (FSS) contract, GSA Schedule 70 SIN 132 51 Information Technology Professional Services, set aside for small business.
