### ISSUE TITLE
Backlog of functionality to include in review

### ISSUE THREAD

**Issue by kfang123** [18F/tts-buy-code-review#2]
# Question/Comment

## Name and affiliation
{please provide information about your job/role in the acquistion process as well as your organization} 
Ken Fang, President, Mobomo

## Section of RFQ documents
Section 9.1 Required Work

## Question/Comment
The RFQ mentions that the vendor must “Review the entire codebase (approximately 29,869 lines of code) with a focus on functionality and maintainability.” Is there a backlog of functionality desired and/or is stories found in the github repository and trello project effectively representative of the additional functionality desired

**Comment by stvnrlly** [comment]
Thanks for the question!

Our primary focus is more general, about which portions of the codebase are written extensibly and which portions would be more difficult to extend/refactor. The RFI responses indicated that some reviewers would prefer to work without extra context, while some would prefer to have that context. For a reviewer who prefers context, we do have a set of user stories, weighted by impact, that we can provide.

We were planning to provide those user stories at the time of award, if the reviewer wants them. Would that be sufficient, or do you think the user stories would be a requirement to make an accurate bid?

**Comment by kfang123** [comment]
That should be sufficient. We should be able to still accurately bid as long as desired functionality is documented at a high-level and available. Thanks
